### ISSUE TITLE
Arm machine can`t work, need help.

### ISSUE THREAD

**Issue by ZevaXu** [reorx/sui2#3]
Hi , I build a docker image with the Dockerfile on my arm machine. But it can`t work.

error shows 'standard_init_linux.go:228: exec user process caused: exec format error'.

Do you know what`s the problem.

Thank you.

**Comment by akgnah** [comment]
https://github.com/reorx/sui2/blob/b52df9c93c0b2a3da4e296d18ec4a95faecb8181/Dockerfile#L15

Try changing the `tini` to `tini-armhf` or `tini-arm64` and then build your image again.

Run `uname -m` to check your architecture, then select `tini-armhf` or `tini-arm64`.

This line should look like the following after modification.

`ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-armhf /tini`

or 

`ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-arm64 /tini`

**Comment by reorx** [comment]
This one should be the fix to get the proper tint release for whatever architecture you are using 0786eef

I also added linux/arm64 in the supported images, so that you don't need to build by yourself, unless you are using armhf.

**Comment by reorx** [comment]
I'll close this one for now, if you have any problems, just reply and I'll reopen it

**Comment by ZevaXu** [comment]
I have tried, It works very well. Thanks!
